### ISSUE TITLE
Placement face

### ISSUE THREAD

**Issue by TurkeyMcMac** [Beanzilla/teleporter_tool#2]
I think you can use`pointed_thing.above` to let the player teleport the node to the right place (replicating the behavior of placing a node.) I guess you should also check if the node at `pointed_thing.under` is `buildable_to`, but I haven't checked if you do this already.

**Comment by ApolloX939** [comment]
I don't instead I just obtain a position then add 1 to it's y then place... Kind of blind teleporting. :package: 

> My code also replicates placing... but I really need to develop a better placement system... obtain the above node, if it's a list of valid things (air, water, water source, lava, lava source) then replace, else try obtaining the node below (that would allow placing it on the ceiling)

I should use pointed_thing but I do things differently.

- [x] Investigate if pointed_thing is a better placement method rather than current placement code.
- [x] Possibly update the code to pointed_thing

**Comment by Beanzilla** [comment]
I am working on making code that will analyze if the above node is air or liquid (if so we teleport there) else we try the node below the one we are looking at (This case it would be the ceiling rather than part of the roof)

**Comment by ApolloX939** [comment]
I will update contentdb to have this "new" version. (Look out for v1.2)

**Comment by ApolloX939** [comment]
[v1.2](https://github.com/Beanzilla/teleporter_tool/releases/tag/v1.2)

**Comment by ApolloX939** [comment]
Since it was a bug... but now it's squashed.
